#ifndef VEGA_ENGINE_COMPONENT_TYPE_H
#define VEGA_ENGINE_COMPONENT_TYPE_H

#define VEGA_COMPONENT_TYPE_TRANSFORM        (0ULL)
#define VEGA_COMPONENT_TYPE_CAMERA           (1ULL)
#define VEGA_COMPONENT_TYPE_RENDERABLE       (2ULL)
#define VEGA_COMPONENT_TYPE_SCENE_CONTROLLER (16ULL)

#define VEGA_COMPONENT_BIT_TRANSFORM        (1ULL << VEGA_COMPONENT_TYPE_TRANSFORM)
#define VEGA_COMPONENT_BIT_CAMERA           (1ULL << VEGA_COMPONENT_TYPE_CAMERA)
#define VEGA_COMPONENT_BIT_RENDERABLE       (1ULL << VEGA_COMPONENT_TYPE_RENDERABLE)
#define VEGA_COMPONENT_BIT_SCENE_CONTROLLER (1ULL << VEGA_COMPONENT_TYPE_SCENE_CONTROLLER)

#endif // VEGA_ENGINE_COMPONENT_TYPE_H
